name: sync_main_into_dev

on:
  push:
    branches:
      - main

jobs:
  auto_merge:
    runs-on: ubuntu-latest    
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for all branches
      
      - name: configure_git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions@github.com"

      - name: merge_main_into_dev
        run: |
          git checkout dev
          git merge origin/main --no-edit
          git push origin dev